### ISSUE TITLE
utf-8 转GBK 会报错

### ISSUE THREAD

**Issue by lutaf** [keli/ctp-python#1]
CThostFtdcSettlementInfoConfirmField.Content 字段，最后一段
怀疑所有的 utf8 ->gbk都有问题
在simnow上可以复现

iconv_open 加下面这个//IGNORE

When the string "//IGNORE" is appended to tocode, characters that cannot be represented in the target character set will be silently discarded

**Comment by keli** [comment]
这个是内存管理的问题而不是转码的问题，ctp的库会释放掉它传给你回调函数的东西，当你打印的时候这块内存已经free掉了，当然就转码失败了。这个应该是需要改swig定义这边处理内存的ownership，并把相应的内容拷到python，但是我还没太搞清楚怎么做。我自己的代码里面需要缓存起来的ctp结构只有很少的几处，所以直接手动转成自己定义的python数据类型了，你可以参考一下这个做法，或者有时间研究一下swig能解决这个问题当然更好 :-)

**Comment by lutaf** [comment]
多谢，ctp-python 转换的所有对象都有这个问题, 典型是def OnRtnDepthMarketData(self, pDepthMarketData: 'CThostFtdcDepthMarketDataField'):   要用copy处理， string是基本类型，容易忽视
