### ISSUE TITLE
 import _ctp ImportError: DLL load failed while importing _ctp: 找不到指定的模块。

### ISSUE THREAD

**Issue by kmyface** [keli/ctp-python#10]
Windows10下使用conda创建的python3.11.3按照pip install ctp-python之后,import ctp就跳这个提示.
File "D:\Program\anaconda3\envs\ctp\Lib\site-packages\ctp.py", line 18, in <module>
    import _ctp
ImportError: DLL load failed while importing _ctp: 找不到指定的模块。

**Comment by keli** [comment]
libiconv装了吗
```
conda install -c conda-forge libiconv
```

**Comment by kmyface** [comment]
使用Miniconda3重装了一下可以,之前用anaconda装的就不行.
