### ISSUE TITLE
No module named _ctp

### ISSUE THREAD

**Issue by xy-Ch4mpion** [keli/ctp-python#2]
`Traceback:
ctp.py:22: in swig_import_helper
    return importlib.import_module(mname)
..\..\anaconda3\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:973: in _find_and_load_unlocked
    ???
E   ModuleNotFoundError: No module named '_ctp'

During handling of the above exception, another exception occurred:
..\..\anaconda3\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_trader.py:15: in <module>
    import ctp
ctp.py:25: in <module>
    _ctp = swig_import_helper()
ctp.py:24: in swig_import_helper
    return importlib.import_module('_ctp')
..\..\anaconda3\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named '_ctp'`

How could I deal with this problem?

**Comment by keli** [comment]
Are you on Windows? There are no binaries for windows in the repo... I guess you can download the libraries for windows and try to make it work (it shouldn't be hard, but I personally don't use windows so I never really bothered).

**Comment by keli** [comment]
Download ctp libraries for windows here: http://www.sfit.com.cn/5_2_DocumentDown_2.htm

**Comment by xy-Ch4mpion** [comment]
I'm using linux (Centos7).

**Comment by xy-Ch4mpion** [comment]
______________________________________ ERROR collecting tests/test_trader.py ______________________________________
ImportError while importing test module '/home/xuyichen/test/ctp-python/tests/test_trader.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ctp.py:22: in swig_import_helper
    return importlib.import_module(mname)
/usr/lib64/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:994: in _gcd_import
    ???
<frozen importlib._bootstrap>:971: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
E   ModuleNotFoundError: No module named '_ctp'

During handling of the above exception, another exception occurred:
/usr/lib64/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_trader.py:15: in <module>
    import ctp
ctp.py:25: in <module>
    _ctp = swig_import_helper()
ctp.py:24: in swig_import_helper
    return importlib.import_module('_ctp')
/usr/lib64/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named '_ctp'

When I using Linux, the error lokks like this.

**Comment by keli** [comment]
Linux发行版和版本是？安装的时候有报错吗？方便的话把运行python setup.py install产生的输出贴一下

这个看上去是不知道为什么_ctp.xxxx.so没有拷过去，你可以看一下生成的build目录下有没有相应的文件，如果因为某种原因没有拷贝成功的话，把这个.so拷贝到ctp最终安装目录里面应该就可以了

```
$ ls build/lib.linux-x86_64-3.7/
_ctp.cpython-37m-x86_64-linux-gnu.so  ctp.py  libthostmduserapi_se.so  libthosttraderapi_se.so
```
