### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by easily44** [keli/ctp-python#4]
您好，我在python3.8 setup.py build时遇到了动态库找不到的问题

ctp2_wrap.cpp:419424:107: warning: character constant too long for its type
ctp2_wrap.cpp:419425:105: warning: multi-character character constant [-Wmultichar]
  ..."THOST_FTDC_FTC_BankLaunchBrokerToBank",SWIG_From_char(static_cast< char >('102002')));
                                                                                ^
ctp2_wrap.cpp:419425:105: warning: character constant too long for its type
ctp2_wrap.cpp:419426:107: warning: multi-character character constant [-Wmultichar]
  ..."THOST_FTDC_FTC_BrokerLaunchBrokerToBank",SWIG_From_char(static_cast< char >('202002')));
                                                                                  ^
ctp2_wrap.cpp:419426:107: warning: character constant too long for its type
35 warnings generated.
creating build/lib.macosx-10.9-x86_64-3.8
g++ -bundle -undefined dynamic_lookup -L/Users/xx/opt/anaconda3/lib -arch x86_64 -L/Users/xx/opt/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.9-x86_64-3.8/ctp2_wrap.o -Lapi/6.6.1 -lsttraderapi_se -lstmduserapi_se -o build/lib.macosx-10.9-x86_64-3.8/_ctp2.cpython-38-darwin.so -Wl,-rpath,$ORIGIN

ld: library not found for -lsttraderapi_se
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1

---

系统环境:
macos10.15.7
gcc version 10.3.0
python3.8 anaconda
ctp试过了6.6.5、6.6.1、6.3.19都是同样的报错

**Comment by keli** [comment]
官方就没有提供mac版的动态库

**Comment by easily44** [comment]
谢谢 那我找个centos试试

**Comment by easily44** [comment]
换成centos可以编译打包了，多谢
我在弄弄simnow
