### ISSUE TITLE
centos7 python3.8报错

### ISSUE THREAD

**Issue by liuts** [keli/ctp-python#5]
你好，这是截取了一小部分错误。编译环境是  centos7 python3.8 ，请问你使用的环境是什么版本？

![image](https://user-images.githubusercontent.com/8000832/164879562-d95ac6f4-6cd7-4c10-8328-29d0a1183866.png)

[root@localhost ctp-python]# 
[root@localhost ctp-python]# 

[root@localhost ctp-python]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

**Comment by keli** [comment]
我用Debian。你这个贴的全是warning没有一个是错误信息啊。

**Comment by liuts** [comment]
我重新贴了错误的图。你用的debian是哪个版本的，我把环境弄成和你一样的试试。能加下qq 208428080， 以后进的你的群讨论吗？

**Comment by keli** [comment]
Debian bullseye和上个stable版本buster都编译过，其实这儿原来有个用户也用的centos说弄好了，但是我不知道他什么版本的。你可以按readme里面的方法用swig重新生成一下源码试试，不行再换系统吧。我还没建群，就二十来个关注，先留言就好。

**Comment by keli** [comment]
看了眼错误，可能是你的gcc版本太老，gcc扩展应该是支持variable length的：https://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html

换个新版的gcc或者新系统试试，看你哪个方便吧

**Comment by liuts** [comment]
用了debian系统，编译通过了
