### ISSUE TITLE
可以支持mac系统吗

### ISSUE THREAD

**Issue by yangyueguang** [keli/ctp-python#6]

**Comment by keli** [comment]
官方现在好像是有提供mac库了，有空时我弄看看吧

**Comment by yangyueguang** [comment]
我用你的方法现在可以编译mac系统的so，行情接口是没问题的，交易接口连不上，不知道是不是上期所不支持mac的交易接口

**Comment by keli** [comment]
刚加了mac版6.6.9的支持，编译和import没问题，不过还没实际测，等晚上测看看了

**Comment by keli** [comment]
> 我用你的方法现在可以编译mac系统的so，行情接口是没问题的，交易接口连不上，不知道是不是上期所不支持mac的交易接口


你再试下用我这个吧，官方给的头文件里面ReqUserLogin不知道为啥多了俩参数，我给去掉就好了，可以登录，我在simnow跑了一会儿正常的

setup.py 里 API_VER 改成 6.6.9
然后
`swig -python -py3 -c++ -threads -I./api/6.6.9/darwin -o ctp_wrap.cpp ctp.i`
`python setup.py install`

**Comment by yangyueguang** [comment]
我按你说的方法编译成功之后，行情登录没问题，交易登录闪退。就在self.api.ReqUserLogin(field, self.request_id)这个方法调用的时候。不妨加个微信聊: 2829969299
    def OnRspAuthenticate(self, pRspAuthenticateField, pRspInfo, req_id, last):
        if pRspInfo.ErrorID == 0:
            print('认证成功')
            field = ctp.CThostFtdcReqUserLoginField()
            field.BrokerID = self.broker
            field.UserID = self.id
            field.Password = self.password
            self.md.ReqUserLogin(field, self.request_id)
            print('ddd')
            self.api.ReqUserLogin(field, self.request_id)

**Comment by yangyueguang** [comment]
> > 我用你的方法现在可以编译mac系统的so，行情接口是没问题的，交易接口连不上，不知道是不是上期所不支持mac的交易接口
> 
> 你再试下用我这个吧，官方给的头文件里面ReqUserLogin不知道为啥多了俩参数，我给去掉就好了，可以登录，我在simnow跑了一会儿正常的
> 
> setup.py 里 API_VER 改成 6.6.9 然后 `swig -python -py3 -c++ -threads -I./api/6.6.9/darwin -o ctp_wrap.cpp ctp.i` `python setup.py install`

交易登录闪退

**Comment by keli** [comment]
> 交易登录闪退

我是m1 mac，os和xcode都最新版。闪退这种事我也没办法，我没空帮别人调试，你自己找找原因吧，可以留言讨论
