### ISSUE TITLE
ImportError: DLL load failed while importing _ctp: 找不到指定的模块

### ISSUE THREAD

**Issue by bitswall** [keli/ctp-python#7]
I try to install this module on windows 11 64bits.

1. conda create --name python_ctp python==3.11
2. pip install ctp-python==6.6.9(installed successfully )
3. 从windows命令行运行python
4. import ctp， 报错：
ImportError: DLL load failed while importing _ctp: 找不到指定的模块

感觉安装很简单，pip install也没有任何报错，为什么回报错？

**Comment by keli** [comment]
哦，应该是windows用conda编译的时候版本指定得有点问题，后面我有空修改重新上传一下，先用python 3.9.x吧，目前只有这个可以。

**Comment by keli** [comment]
哦，我又看了一下，应该是conda新建的env没有装libiconv导致的
```
conda install -c conda-forge libiconv
```
然后应该就可以了
