### ISSUE TITLE
在MacOS使用该接口，我应该下载MacOS版本的CTP API还是linux版本的？

### ISSUE THREAD

**Issue by archerhu77** [keli/ctp-python#9]
我今天才知道上期技术出了MacOS版本的CTP API，看了一下不知道从何入手（因为跟以前在linux用的很不一样），刚好搜索到你这个项目，也是有点迷糊，所以请教，谢谢

**Comment by archerhu77** [comment]
我自己也编译成功了，但是调用的时候遇到ModuleNotFoundError: No module named '_thosttraderapi'

**Comment by keli** [comment]
为啥不直接pip install ctp-python呢

**Comment by archerhu77** [comment]
> 为啥不直接pip install ctp-python呢

后来是这么做了，但是调用库又遇上了AttributeError: 'function' object has no attribute 'connected'

**Comment by keli** [comment]
你不贴代码，没法知道是什么问题。参考一下 tests目录下的文件吧，ctp库的用法都大差不差
https://github.com/keli/ctp-python/tree/master/tests

**Comment by archerhu77** [comment]
> 你不贴代码，没法知道是什么问题。参考一下 tests目录下的文件吧，ctp库的用法都大差不差 https://github.com/keli/ctp-python/tree/master/tests

我就是用tests目录的test_trader.py加了几句自己simnow账号信息测试的，如下：


```
#!/usr/bin/env python
import ctp
import pytest
import sys
import time
import hashlib
import tempfile
import os, os.path
import threading
import datetime


@pytest.fixture(scope="module")
def spi(front, broker, user, password, app, auth):
    assert front and broker and user and password and app and auth, "missing arguments"
    _spi = TraderSpi(front, broker, user, password, app, auth)
    th = threading.Thread(target=_spi.run)
    th.daemon = True
    th.start()
    secs = 5
    while secs:
        if not (_spi.connected and _spi.authed and _spi.loggedin):
            secs -= 1
            time.sleep(1)
        else:
            break    
    return _spi


class TraderSpi(ctp.CThostFtdcTraderSpi):
    def __init__(self, front, broker_id, user_id, password, app_id, auth_code):
        ctp.CThostFtdcTraderSpi.__init__(self)

        self.front = front
        self.broker_id = broker_id
        self.user_id = user_id
        self.password = password
        self.app_id = app_id
        self.auth_code = auth_code

        self.request_id = 0
        self.connected = False
        self.authed = False
        self.loggedin = False

        self.api = self.create()

        # 添加调试语句
        print(f"TraderSpi created with parameters: front={front}, broker_id={broker_id}, user_id={user_id}, password={password}, app_id={app_id}, auth_code={auth_code}")


    def create(self):
        dir = ''.join(('ctp', self.broker_id, self.user_id)).encode('UTF-8')
        dir = hashlib.md5(dir).hexdigest()
        dir = os.path.join(tempfile.gettempdir(), dir, 'Trader') + os.sep
        if not os.path.isdir(dir): os.makedirs(dir)
        return ctp.CThostFtdcTraderApi.CreateFtdcTraderApi(dir)

    def run(self):
        self.api.RegisterSpi(self)
        self.api.RegisterFront(self.front)
        self.api.Init()
        self.api.Join()

    def auth(self):
        field = ctp.CThostFtdcReqAuthenticateField()
        field.BrokerID = self.broker_id
        field.UserID = self.user_id
        field.AppID = self.app_id
        field.AuthCode = self.auth_code
        self.request_id += 1
        self.api.ReqAuthenticate(field, self.request_id)

    def login(self):
        field = ctp.CThostFtdcReqUserLoginField()
        field.BrokerID = self.broker_id
        field.UserID = self.user_id
        field.Password = self.password
        self.request_id += 1
        self.api.ReqUserLogin(field, self.request_id)

    def OnFrontConnected(self):
        print("OnFrontConnected")
        self.connected = True
        self.auth()
        print('try auth.')

    def OnRspAuthenticate(self, pRspAuthenticateField:'CThostFtdcRspAuthenticateField', pRspInfo:'CThostFtdcRspInfoField', nRequestID:'int', bIsLast:'bool'):
        print("OnRspAuthenticate:", pRspInfo.ErrorID, pRspInfo.ErrorMsg)
        if pRspInfo.ErrorID == 0:
            self.authed = True
            self.login()
            print('try login.')

    def OnRspUserLogin(self, pRspUserLogin:'CThostFtdcRspUserLoginField', pRspInfo:'CThostFtdcRspInfoField', nRequestID:'int', bIsLast:'bool'):
        print("OnRspUserLogin", pRspInfo.ErrorID, pRspInfo.ErrorMsg)
        if pRspInfo.ErrorID == 0:
            self.loggedin = True
            print('login success.')

    def OnRspError(self, pRspInfo:'CThostFtdcRspInfoField', nRequestID:'int', bIsLast:'bool'):
        print("OnRspError:", pRspInfo.ErrorID, pRspInfo.ErrorMsg)

    def __del__(self):
        self.api.RegisterSpi(None)
        self.api.Release()


def test_init(spi):
    assert spi.connected and spi.authed and spi.loggedin    


front="tcp://180.168.146.187:10100"

broker="9999"
user="123456"           #simnow账号
password="password"     #simnow密码

app="simnow_client_test"
auth="0000000000000000"

test_init(spi)
```

运行报的错误是assert spi.connected and spi.authed and spi.loggedin，看了一下TraderSpi类确实没有connected，这是要在类里加变量？

**Comment by keli** [comment]
要么clone代码库按文档里的测试方法从pytest来跑，要么去掉pytest相关的代码把spi函数里的内容拿出来。spi函数就没有调用过你不觉得奇怪吗，这都是pytest的机制调用的，不要混到一起。仔细观察一下能搞定的。

**Comment by keli** [comment]
不行你再等等吧，我有空时加点例子。

**Comment by archerhu77** [comment]
> 不行你再等等吧，我有空时加点例子。

好的，谢谢您！能请教您用swig封装这个c++ api的一些操作吗？

**Comment by archerhu77** [comment]
我改了一下代码，可以连上了，不过报段错误，我自己排查吧，谢谢

**Comment by keli** [comment]
我让chatgpt改的，现在过交易时间了没法测，应该大差不差吧，你回头自己试试
```
#!/usr/bin/env python
import ctp
import sys
import time
import hashlib
import tempfile
import os, os.path
import threading


class MdSpi(ctp.CThostFtdcMdSpi):

    def __init__(self, front, broker_id, user_id, password):
        ctp.CThostFtdcMdSpi.__init__(self)

        self.front = front
        self.broker_id = broker_id
        self.user_id = user_id
        self.password = password

        self.request_id = 0
        self.connected = False
        self.loggedin = False
        self.subscribed = False
        self.data = None

        self.api = self.create()

    def create(self):
        dir = ''.join(('ctp', self.broker_id, self.user_id)).encode('UTF-8')
        dir = hashlib.md5(dir).hexdigest()
        dir = os.path.join(tempfile.gettempdir(), dir, 'Md') + os.sep
        if not os.path.isdir(dir): os.makedirs(dir)
        return ctp.CThostFtdcMdApi.CreateFtdcMdApi(dir)

    def run(self):
        self.api.RegisterSpi(self)
        self.api.RegisterFront(self.front)
        self.api.Init()
        self.api.Join()

    def login(self):
        field = ctp.CThostFtdcReqUserLoginField()
        field.BrokerID = self.broker_id
        field.UserID = self.user_id
        field.Password = self.password
        self.request_id += 1
        self.api.ReqUserLogin(field, self.request_id)

    def OnFrontConnected(self):
        print("OnFrontConnected")
        self.connected = True
        self.login()

    def OnRspUserLogin(self, pRspUserLogin: 'CThostFtdcRspUserLoginField',
                       pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',
                       bIsLast: 'bool'):
        print("OnRspUserLogin", pRspInfo.ErrorID, pRspInfo.ErrorMsg)
        if pRspInfo.ErrorID == 0:
            self.loggedin = True

    def OnRspError(self, pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',
                   bIsLast: 'bool'):
        print("OnRspError:", pRspInfo.ErrorID, pRspInfo.ErrorMsg)

    def OnRspSubMarketData(
            self, pSpecificInstrument: 'CThostFtdcSpecificInstrumentField',
            pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',
            bIsLast: 'bool'):
        print("OnRspSubMarketData:", pRspInfo.ErrorID, pRspInfo.ErrorMsg)
        if pRspInfo.ErrorID == 0:
            self.subscribed = True

    def OnRtnDepthMarketData(
            self, pDepthMarketData: 'CThostFtdcDepthMarketDataField'):
        print("OnRtnDepthMarketData:", pDepthMarketData)
        self.data = pDepthMarketData

    def __del__(self):
        self.api.RegisterSpi(None)
        self.api.Release()


class TraderSpi(ctp.CThostFtdcTraderSpi):

    def __init__(self, front, broker_id, user_id, password, app_id, auth_code):
        ctp.CThostFtdcTraderSpi.__init__(self)

        self.front = front
        self.broker_id = broker_id
        self.user_id = user_id
        self.password = password
        self.app_id = app_id
        self.auth_code = auth_code

        self.request_id = 0
        self.connected = False
        self.authed = False
        self.loggedin = False

        self.api = self.create()

    def create(self):
        dir = ''.join(('ctp', self.broker_id, self.user_id)).encode('UTF-8')
        dir = hashlib.md5(dir).hexdigest()
        dir = os.path.join(tempfile.gettempdir(), dir, 'Trader') + os.sep
        if not os.path.isdir(dir): os.makedirs(dir)
        return ctp.CThostFtdcTraderApi.CreateFtdcTraderApi(dir)

    def run(self):
        self.api.RegisterSpi(self)
        self.api.RegisterFront(self.front)
        self.api.Init()
        self.api.Join()

    def auth(self):
        field = ctp.CThostFtdcReqAuthenticateField()
        field.BrokerID = self.broker_id
        field.UserID = self.user_id
        field.AppID = self.app_id
        field.AuthCode = self.auth_code
        self.request_id += 1
        self.api.ReqAuthenticate(field, self.request_id)

    def login(self):
        field = ctp.CThostFtdcReqUserLoginField()
        field.BrokerID = self.broker_id
        field.UserID = self.user_id
        field.Password = self.password
        self.request_id += 1
        self.api.ReqUserLogin(field, self.request_id)

    def OnFrontConnected(self):
        print("OnFrontConnected")
        self.connected = True
        self.auth()

    def OnRspAuthenticate(
            self, pRspAuthenticateField: 'CThostFtdcRspAuthenticateField',
            pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',
            bIsLast: 'bool'):
        print("OnRspAuthenticate:", pRspInfo.ErrorID, pRspInfo.ErrorMsg)
        if pRspInfo.ErrorID == 0:
            self.authed = True
            self.login()

    def OnRspUserLogin(self, pRspUserLogin: 'CThostFtdcRspUserLoginField',
                       pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',
                       bIsLast: 'bool'):
        print("OnRspUserLogin", pRspInfo.ErrorID, pRspInfo.ErrorMsg)
        if pRspInfo.ErrorID == 0:
            self.loggedin = True

    def OnRspError(self, pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',
                   bIsLast: 'bool'):
        print("OnRspError:", pRspInfo.ErrorID, pRspInfo.ErrorMsg)

    def __del__(self):
        self.api.RegisterSpi(None)
        self.api.Release()


def create_spi(spi_class, front, broker, user, password, app=None, auth=None):
    if spi_class == TraderSpi:
        assert app and auth, "App and Auth are required for TraderSpi"
        spi = spi_class(front, broker, user, password, app, auth)
    else:
        spi = spi_class(front, broker, user, password)

    th = threading.Thread(target=spi.run)
    th.daemon = True
    th.start()

    secs = 5
    while secs:
        if spi_class == TraderSpi:
            condition = spi.connected and spi.authed and spi.loggedin
        else:
            condition = spi.connected and spi.loggedin

        if not condition:
            secs -= 1
            time.sleep(1)
        else:
            break

    if not condition:
        raise RuntimeError("Initialization failed for " + spi_class.__name__)

    return spi


def run_long_running(trader_front, md_front, broker, user, password, app, auth,
                     instruments):
    trader_spi = create_spi(TraderSpi, trader_front, broker, user, password,
                            app, auth)
    print("Trader SPI initialized and running.")

    md_spi = create_spi(MdSpi, md_front, broker, user, password)
    print("Market Data SPI initialized and running.")

    md_spi.api.SubscribeMarketData(instruments)
    print(f"Subscribed to market data for {instruments}")

    try:
        # Long-running loop
        while True:
            # You can add logic here to process the market data or trader updates
            time.sleep(1)  # Sleep to avoid busy waiting
    except KeyboardInterrupt:
        print("Shutting down.")


# Example usage
if __name__ == "__main__":
    # Replace these with your actual parameters
    trader_front = "your_trader_front"
    md_front = "your_md_front"
    broker = "your_broker"
    user = "your_user"
    password = "your_password"
    app = "your_app"
    auth = "your_auth"
    instruments = ["your_instrument1", "your_instrument2"]

    run_long_running(trader_front, md_front, broker, user, password, app, auth,
                     instruments)
```

**Comment by archerhu77** [comment]
谢谢！我试了可以运行，最后也是跟我之前改的那个一样段错误，我自己想想怎么排查吧




Archer
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keli/ctp-python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月26日(星期二) 下午4:40
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [keli/ctp-python] 在MacOS使用该接口，我应该下载MacOS版本的CTP API还是linux版本的？ (Issue #9)





 
我让chatgpt改的，现在过交易时间了没法测，应该大差不差吧，你回头自己试试
 #!/usr/bin/env python import ctp import sys import time import hashlib import tempfile import os, os.path import threading class MdSpi(ctp.CThostFtdcMdSpi):     def __init__(self, front, broker_id, user_id, password):         ctp.CThostFtdcMdSpi.__init__(self)         self.front = front         self.broker_id = broker_id         self.user_id = user_id         self.password = password         self.request_id = 0         self.connected = False         self.loggedin = False         self.subscribed = False         self.data = None         self.api = self.create()     def create(self):         dir = ''.join(('ctp', self.broker_id, self.user_id)).encode('UTF-8')         dir = hashlib.md5(dir).hexdigest()         dir = os.path.join(tempfile.gettempdir(), dir, 'Md') + os.sep         if not os.path.isdir(dir): os.makedirs(dir)         return ctp.CThostFtdcMdApi.CreateFtdcMdApi(dir)     def run(self):         self.api.RegisterSpi(self)         self.api.RegisterFront(self.front)         self.api.Init()         self.api.Join()     def login(self):         field = ctp.CThostFtdcReqUserLoginField()         field.BrokerID = self.broker_id         field.UserID = self.user_id         field.Password = self.password         self.request_id += 1         self.api.ReqUserLogin(field, self.request_id)     def OnFrontConnected(self):         print("OnFrontConnected")         self.connected = True         self.login()     def OnRspUserLogin(self, pRspUserLogin: 'CThostFtdcRspUserLoginField',                        pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',                        bIsLast: 'bool'):         print("OnRspUserLogin", pRspInfo.ErrorID, pRspInfo.ErrorMsg)         if pRspInfo.ErrorID == 0:             self.loggedin = True     def OnRspError(self, pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',                    bIsLast: 'bool'):         print("OnRspError:", pRspInfo.ErrorID, pRspInfo.ErrorMsg)     def OnRspSubMarketData(             self, pSpecificInstrument: 'CThostFtdcSpecificInstrumentField',             pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',             bIsLast: 'bool'):         print("OnRspSubMarketData:", pRspInfo.ErrorID, pRspInfo.ErrorMsg)         if pRspInfo.ErrorID == 0:             self.subscribed = True     def OnRtnDepthMarketData(             self, pDepthMarketData: 'CThostFtdcDepthMarketDataField'):         print("OnRtnDepthMarketData:", pDepthMarketData)         self.data = pDepthMarketData     def __del__(self):         self.api.RegisterSpi(None)         self.api.Release() class TraderSpi(ctp.CThostFtdcTraderSpi):     def __init__(self, front, broker_id, user_id, password, app_id, auth_code):         ctp.CThostFtdcTraderSpi.__init__(self)         self.front = front         self.broker_id = broker_id         self.user_id = user_id         self.password = password         self.app_id = app_id         self.auth_code = auth_code         self.request_id = 0         self.connected = False         self.authed = False         self.loggedin = False         self.api = self.create()     def create(self):         dir = ''.join(('ctp', self.broker_id, self.user_id)).encode('UTF-8')         dir = hashlib.md5(dir).hexdigest()         dir = os.path.join(tempfile.gettempdir(), dir, 'Trader') + os.sep         if not os.path.isdir(dir): os.makedirs(dir)         return ctp.CThostFtdcTraderApi.CreateFtdcTraderApi(dir)     def run(self):         self.api.RegisterSpi(self)         self.api.RegisterFront(self.front)         self.api.Init()         self.api.Join()     def auth(self):         field = ctp.CThostFtdcReqAuthenticateField()         field.BrokerID = self.broker_id         field.UserID = self.user_id         field.AppID = self.app_id         field.AuthCode = self.auth_code         self.request_id += 1         self.api.ReqAuthenticate(field, self.request_id)     def login(self):         field = ctp.CThostFtdcReqUserLoginField()         field.BrokerID = self.broker_id         field.UserID = self.user_id         field.Password = self.password         self.request_id += 1         self.api.ReqUserLogin(field, self.request_id)     def OnFrontConnected(self):         print("OnFrontConnected")         self.connected = True         self.auth()     def OnRspAuthenticate(             self, pRspAuthenticateField: 'CThostFtdcRspAuthenticateField',             pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',             bIsLast: 'bool'):         print("OnRspAuthenticate:", pRspInfo.ErrorID, pRspInfo.ErrorMsg)         if pRspInfo.ErrorID == 0:             self.authed = True             self.login()     def OnRspUserLogin(self, pRspUserLogin: 'CThostFtdcRspUserLoginField',                        pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',                        bIsLast: 'bool'):         print("OnRspUserLogin", pRspInfo.ErrorID, pRspInfo.ErrorMsg)         if pRspInfo.ErrorID == 0:             self.loggedin = True     def OnRspError(self, pRspInfo: 'CThostFtdcRspInfoField', nRequestID: 'int',                    bIsLast: 'bool'):         print("OnRspError:", pRspInfo.ErrorID, pRspInfo.ErrorMsg)     def __del__(self):         self.api.RegisterSpi(None)         self.api.Release() def create_spi(spi_class, front, broker, user, password, app=None, auth=None):     if spi_class == TraderSpi:         assert app and auth, "App and Auth are required for TraderSpi"         spi = spi_class(front, broker, user, password, app, auth)     else:         spi = spi_class(front, broker, user, password)     th = threading.Thread(target=spi.run)     th.daemon = True     th.start()     secs = 5     while secs:         if spi_class == TraderSpi:             condition = spi.connected and spi.authed and spi.loggedin         else:             condition = spi.connected and spi.loggedin         if not condition:             secs -= 1             time.sleep(1)         else:             break     if not condition:         raise RuntimeError("Initialization failed for " + spi_class.__name__)     return spi def run_long_running(trader_front, md_front, broker, user, password, app, auth,                      instruments):     trader_spi = create_spi(TraderSpi, trader_front, broker, user, password,                             app, auth)     print("Trader SPI initialized and running.")     md_spi = create_spi(MdSpi, md_front, broker, user, password)     print("Market Data SPI initialized and running.")     md_spi.api.SubscribeMarketData(instruments)     print(f"Subscribed to market data for {instruments}")     try:         # Long-running loop         while True:             # You can add logic here to process the market data or trader updates             time.sleep(1)  # Sleep to avoid busy waiting     except KeyboardInterrupt:         print("Shutting down.") # Example usage if __name__ == "__main__":     # Replace these with your actual parameters     trader_front = "your_trader_front"     md_front = "your_md_front"     broker = "your_broker"     user = "your_user"     password = "your_password"     app = "your_app"     auth = "your_auth"     instruments = ["your_instrument1", "your_instrument2"]     run_long_running(trader_front, md_front, broker, user, password, app, auth,                      instruments)
